### ISSUE TITLE
Connect mysql failed Error 1130: Host '127.0.0.1'

### ISSUE THREAD

**Issue by CrookedPotato** [liuhr/my2sql#11]
MySQL：Server version: 8.0.21
go version go1.15.5 linux/amd64

认证
| root               | mysql_native_password |

[root@us-prod-dba-dbbackup my2sql]# ./my2sql  -user root -password  -port 3306 -host 10.0.4.177 -databases tstn  -taaa -work-type rollback   -start-file mysql-bin.000525 -start-datetime "2021-06-24 13:10:43" --stop-datetime "2021-06-24 13:15:43" -output-dir sql/

[2021/06/24 14:29:13] [fatal] context.go:575 Connect mysql failed Error 1130: Host '127.0.0.1' is not allowed to connect to this MySQL server

为啥连接的是127.0.0.1  还是使用错误了？

**Comment by liujunjia1996** [comment]
所有有特殊字符的地方都加上引号就好了
