### ISSUE TITLE
各种错误

### ISSUE THREAD

**Issue by jiangnanora** [liuhr/my2sql#17]
/opt/my2sql  -user xxx  -password 'xxx' -host 127.0.0.1   -port 3310 -mode file -local-binlog-file ./mysql-bin.000015   -work-type stats  -start-file mysql-bin.000015  -start-datetime "2021-10-08 10:20:00" -stop-datetime "2021-10-08 11:00:00"  -big-trx-row-limit 500 -long-trx-seconds 300   -output-dir ./tmpdir

1、时间不兼容: 希望能自动补全
[2021/10/08 14:44:43] [fatal] context.go:290 invalid start datetime -start-datetime 2021-10-8 10:20:0

2、样例参数，报错信息看不懂，范围1到10，默认30000
[2021/10/08 14:45:07] [fatal] context.go:462 value of -b out of range: 500 is specfied, but Valid values range from 1 to 10, default 30000

类似的还有：
[2021/10/08 14:48:59] [fatal] context.go:462 value of -l out of range: 300 is specfied, but Valid values range from 0 to 1, default 3600

![image](https://user-images.githubusercontent.com/20857328/136520934-9932ca32-26ef-41c4-aa92-1a3742f870b2.png)
看不明白，为什么要限制在1到10，难到不可以大于20吗？

3、解析出来结果，看不出化了多少时间
mysql-bin.000016  2021-10-08_15:29:21 2021-10-08_15:29:21 55532604   110556152  1835008  0          [testdb.student(inserts=1835008, updates=0, deletes=0)]

实际执行：
[root@mysql_3310.sock][testdb]> insert into student(number,name,add_time,content) select number,name,add_time,content from student;
Query OK, 1835008 rows affected (23.53 sec)
Records: 1835008  Duplicates: 0  Warnings: 0

**Comment by oraclescjx** [comment]
2、样例参数，报错信息看不懂，范围1到10，默认30000
这个问题可能是定义的问题，我修改为如下即可。
		//"BigTrxRowLimit": []int{1, 10, 30000, 500},
		//"LongTrxSeconds": []int{0, 1, 3600, 300},
		"BigTrxRowLimit": []int{1, 30000, 500},
		"LongTrxSeconds": []int{0, 3600, 300},
		
3、解析出来结果，看不出化了多少时间

这个问题在biglong_trx.txt应该是有耗时时间的，应该是第2个问题的影响，导致日志统计有问题。

binlog            starttime           stoptime            startpos   stoppos    rows     duration   tables
mysql_binlog.017443 2021-10-12_01:20:40 2021-10-12_01:20:54  129027735  129797560  1000     14         [dbname.xxx(inserts=0, updates=0, deletes=1000)]

**Comment by jiangnanora** [comment]
> 3、解析出来结果，看不出化了多少时间
> 
> 这个问题在biglong_trx.txt应该是有耗时时间的，以秒为统计粒度2021-10-08_15:29:21 2021-10-08_15:29:21 不到1秒就按0计算。
> 
> binlog starttime stoptime startpos stoppos rows duration tables mysql_binlog.017443 2021-10-12_01:20:40 2021-10-12_01:20:54 129027735 129797560 1000 14 [dbname.xxx(inserts=0, updates=0, deletes=1000)]

执行为18秒哎，按你的解释为0秒？

**Comment by flyingonthebed** [comment]
跟你个贴，大事务时间只能传0～1，默认3600s，什么奇葩逻辑。

**Comment by liuhr** [comment]
> 

这个已修复
