### ISSUE TITLE
分数位time类型字段解析失败

### ISSUE THREAD

**Issue by mdp1230** [liuhr/my2sql#2]
5.7版本time类型解析正常。
time(3) time(6)解析结果失败，解析结果为'00:00:00'

**Comment by liuhr** [comment]
my2sql引用了 https://github.com/siddontang的binlog解析库，这个库当前还不支持time类型数据解析，
相关bug：https://github.com/siddontang/go-mysql/issues/515

**Comment by liuhr** [comment]
my2sql引用了 github.com/siddontang的binlog解析库，这个库当前还不支持time类型数据解析，相关bug：https://github.com/siddontang/go-mysql/issues/515

**Comment by mdp1230** [comment]
赞！！！
