### ISSUE TITLE
统计DML操作量出错

### ISSUE THREAD

**Issue by EliLiu-YF** [liuhr/my2sql#27]
context.go:462 value of -l out of range: 5 is specfied, but Valid values range from 0 to 1, default 3600

/root/lyf/my2sql  -user hotdb_datasource -password hotdb_datasource -host 127.0.0.1   -port 3311 -mode repl -work-type stats  -start-file mysql-bin.020070  -start-datetime "2022-03-17 08:30:00" -stop-datetime "2022-03-17 08:43:00"  -big-trx-row-limit 5 -long-trx-seconds 5   -output-dir /root/lyf

**Comment by liuhr** [comment]
已修复
