### ISSUE TITLE
编译出错

### ISSUE THREAD

**Issue by WQMysqlDBA** [liuhr/my2sql#29]
# my2sql/base
base/file.go:134:23: this.Parser.ParseHeader undefined (type *replication.BinlogParser has no field or method ParseHeader)
base/file.go:171:23: this.Parser.ParseEvent undefined (type *replication.BinlogParser has no field or method ParseEvent)

代码里怎么缺了这个func啊

**Comment by WQMysqlDBA** [comment]
看了下是replication包利民啊这两个函数都是小写。。。emmm

**Comment by WQMysqlDBA** [comment]
解决了

**Comment by gerdong** [comment]
怎么解决的呢？说一下啊
