### ISSUE TITLE
库名带-会报错

### ISSUE THREAD

**Issue by gj19910723** [liuhr/my2sql#30]
[2022/07/11 17:35:24] [fatal] sqlgen.go:324 Fail to generate update sql for bi-report.QRTZ_SCHEDULER_STATE mysql-bin.001840 1610282-1610529 
	error: Invalid database name specified
ORIGINAL STACK TRACE:
my2sql/sqlbuilder.(*updateStatementImpl).String
	/root/go/src/my2sql/sqlbuilder/statement.go:702 +0x66c062
my2sql/base.GenUpdateSqlsForOneRowsEvent
	/root/go/src/my2sql/base/sqlgen.go:322 +0x69fdf0
my2sql/base.GenForwardRollbackSqlFromBinEvent
	/root/go/src/my2sql/base/events.go:151 +0x69083e
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1371 +0x46c1c0

	rows data:[RuoyiScheduler bi-report-client_sit1648115311244 1657529390600 15000]
[RuoyiScheduler bi-report-client_sit1648115311244 1657529405601 15000]

**Comment by liuhr** [comment]
这个错误是引用的外部开源库sqlbuilder报出的异常，数据库名应该包含了特殊字符，这个bug暂时修不了。
