### ISSUE TITLE
int(11) unsigned 解析错误

### ISSUE THREAD

**Issue by yqMac** [liuhr/my2sql#31]
int(11) unsigned 类型会被解析成负值，插入的时候就异常了

**Comment by zhenxingCN** [comment]
我理解对于int类型(包含tinyint到bigint) 他们的最大值在binlog中用的 -1(_实际最大值_)这种形式,工具没解析正确,这个在binlog2sql解析时是进行了处理

![image](https://user-images.githubusercontent.com/23207447/183036352-8f2141fb-eaa4-48fb-bb2f-6a1974907853.png)

**Comment by liuhr** [comment]
这个会尽快修复的。
