### ISSUE TITLE
为什么统计大事务的时候  Duration 值都是0？

### ISSUE THREAD

**Issue by yaobo-lab** [liuhr/my2sql#32]
![image](https://user-images.githubusercontent.com/21329253/188775081-6f41627e-c58a-4721-b6d2-34b6246a4f74.png)

为什么 分析大事务的时候。duration 值都是 0 

还有： starttime stoptime 两个字段是代码是什么？

为什么统计大事务的时候  Duration 值都是0？

**Comment by cheungfeifu** [comment]
starttime stoptime 两个字段 应该是事务的开启和关闭时间吧
