### ISSUE TITLE
引用的 go-mysql-org 内被修改，导致编译未通过问题

### ISSUE THREAD

**Issue by dibrother** [liuhr/my2sql#33]
<img width="898" alt="image" src="https://user-images.githubusercontent.com/95730552/198444589-b604a965-ca63-4490-af5e-b62152e20839.png">

大佬，你这块改下被，改成自己新建个go文件去引用，而非直接去改这个引用项目内的代码，这个会导致 git下来后，编译找不到此方法

```
base/file.go:134:14: this.Parser.h undefined (type *replication.BinlogParser has no field or method h)
base/file.go:135:10: cannot assign *replication.EventHeader to this.Parser.h in multiple assignment
```

**Comment by dba-ws** [comment]
楼上的大佬，我也遇到了同样的问题，请问您是怎么解决的？我想学习一下

**Comment by liuhr** [comment]
已经使用go mod管理package，没有这个问题了
