### ISSUE TITLE
无法连接8.0.22实例

### ISSUE THREAD

**Issue by aaron8219** [liuhr/my2sql#4]
**MySQL版本和用户信息**
mysql> \s

/usr/local/mysql8/bin/mysql  Ver 8.0.22 for Linux on x86_64 (MySQL Community Server - GPL)

Connection id:		33
Current database:	
Current user:		zlm@dmp1
SSL:			Cipher in use is TLS_AES_256_GCM_SHA384
Current pager:		stdout
Using outfile:		''
Using delimiter:	;
Server version:		8.0.22 MySQL Community Server - GPL
Protocol version:	10
Connection:		10.186.60.62 via TCP/IP
Server characterset:	utf8
Db     characterset:	utf8
Client characterset:	utf8mb4
Conn.  characterset:	utf8mb4
TCP port:		3307
Binary data as:		Hexadecimal
Uptime:			16 hours 53 min 56 sec

Threads: 1  Questions: 102  Slow queries: 0  Opens: 283  Flush tables: 4  Open tables: 93  Queries per second avg: 0.001

mysql> select user(),current_user();
+----------+----------------+
| user()   | current_user() |
+----------+----------------+
| zlm@dmp1 | zlm@%          |
+----------+----------------+
1 row in set (0.00 sec)

**测试1**
使用8.0默认认证方式的用户连接（plugin为caching_sha2_password，权限为all）
mysql>  select user,host,plugin from mysql.user where user='zlm';
+------------------+-----------+-----------------------+
| user             | host      | plugin                |
+------------------+-----------+-----------------------+
| zlm              | %         | caching_sha2_password |
+------------------+-----------+-----------------------+
1 rows in set (0.00 sec)

09:37 AM zhlm1 (master) ~# ./my2sql -user zlm -password zlm -host 10.186.60.62 -port 3307 -start-file mysql-bin.000001 -start-datetime "2020-12-23 17:20:00" -stop-datetime "2020-12-23 18:00:00" -output-dir /tmp
[2020/12/24 09:37:46] [fatal] context.go:532 Connect mysql failed this authentication plugin is not supported

**测试2**
使用旧的认证方式用户进行连接（创建用户时用with指定plugin为mysql_native_password，权限为all）
mysql> select user,host,plugin from mysql.user where user='zlm';
+------------------+-----------+-----------------------+
| user             | host      | plugin                |
+------------------+-----------+-----------------------+
| zlm              | %         | mysql_native_password |
+------------------+-----------+-----------------------+
1 rows in set (0.01 sec)

09:41 AM dmp1 (master) ~# ./my2sql -user zlm -password zlm -host 10.186.60.62 -port 3307 -start-file mysql-bin.000001 -start-datetime "2020-12-23 17:20:00" -stop-datetime "2020-12-23 18:00:00" -output-dir /tmp
[2020/12/24 09:57:01] [fatal] context.go:532 Connect mysql failed this user requires mysql native password authentication.

**疑问**
改了认证方式为5.7的mysql_native_password仍然报错，请问目前该工具是否还不支持8.0？

**Comment by liuhr** [comment]
[(none)]>select user,host,plugin from mysql.user where user='testuser';
+----------+------+-----------------------+
| user     | host | plugin                |
+----------+------+-----------------------+
| testuser | %    | caching_sha2_password |
+----------+------+-----------------------+


./my2sql -user testuser -password 123456 -port 3306 -host 127.0.0.1   -start-file "mysql-bin.000002" -work-type 2sql  -output-dir ./tmpdir/
[2020/12/28 15:39:40] [fatal] context.go:532 Connect mysql failed this authentication plugin is not supported


[(none)]>alter user testuser@'%' identified with mysql_native_password by '123456';

[(none)]>select user,host,plugin from mysql.user where user='testuser';
+----------+------+-----------------------+
| user     | host | plugin                |
+----------+------+-----------------------+
| testuser | %    | mysql_native_password |
+----------+------+-----------------------+


./my2sql -user testuser -password 123456 -port 3306 -host 127.0.0.1   -start-file "mysql-bin.000002" -work-type 2sql  -output-dir ./tmpdir/
[2020/12/28 15:45:59] [info] events.go:58 start thread 2 to generate redo/rollback sql
[2020/12/28 15:45:59] [info] binlogsyncer.go:144 create BinlogSyncer with config {1113306 mysql bjm6-dba-mysql-v8-a001.prod.bjm6.momo.com 10635 testuser   utf8 false false <nil> false Local false 0 0s 0s 0 false false 0}
[2020/12/28 15:45:59] [info] binlogsyncer.go:360 begin to sync binlog from position (mysql-bin.000002, 4)
[2020/12/28 15:45:59] [info] events.go:208 start thread to write redo/rollback sql into file
[2020/12/28 15:45:59] [info] stats_process.go:166 start thread to analyze statistics from binlog
[2020/12/28 15:45:59] [info] events.go:58 start thread 1 to generate redo/rollback sql
[2020/12/28 15:45:59] [info] repl.go:15 start to get binlog from mysql
[2020/12/28 15:45:59] [info] binlogsyncer.go:777 rotate to (mysql-bin.000002, 4)
[2020/12/28 15:46:01] [info] events.go:242 finish processing mysql-bin.000002 10486284
[2020/12/28 15:46:07] [info] repl.go:83 deadline exceeded.
[2020/12/28 15:46:07] [info] repl.go:17 finish getting binlog from mysql
[2020/12/28 15:46:07] [info] stats_process.go:266 exit thread to analyze statistics from binlog
[2020/12/28 15:46:07] [info] events.go:183 exit thread 2 to generate redo/rollback sql
[2020/12/28 15:46:07] [info] events.go:183 exit thread 1 to generate redo/rollback sql
[2020/12/28 15:46:07] [info] events.go:272 finish writing redo/forward sql into file
[2020/12/28 15:46:07] [info] events.go:275 exit thread to write redo/rollback sql into file

**Comment by zzxcong** [comment]
![image](https://user-images.githubusercontent.com/46800785/103637378-609c4c80-4f86-11eb-8f12-9433178b16d0.png)
w我测试的 8.0.21 也是不行

**Comment by liuhr** [comment]
能提供下8.0.21 mysql配置文件吗

**Comment by zzxcong** [comment]
[client]
port	= 3306
socket	= /home/mysqlfile/mysqldata80/mysql.sock

[mysql]
prompt="\u@xingxiao-luohetest-5-211 \R:\m:\s [\d]> "
no-auto-rehash

[mysqld]
user	= mysql
port	= 3306
basedir	= /usr/local/mysql80
datadir	= /home/mysqlfile/mysqldata80
socket	= /home/mysqlfile/mysqldata80/mysql.sock
pid-file = xingxiao-luohetest-5-211.pid
character-set-server = utf8mb4
skip_name_resolve = 1
log_error_verbosity=2


#若你的MySQL数据库主要运行在境外，请务必根据实际情况调整本参数
default_time_zone = "+8:00"

open_files_limit    = 65535
back_log = 1024
max_connections = 512
max_connect_errors = 1000000
table_open_cache = 1024
table_definition_cache = 1024
table_open_cache_instances = 64
thread_stack = 512K
external-locking = FALSE
max_allowed_packet = 32M
sort_buffer_size = 4M
join_buffer_size = 4M
thread_cache_size = 768
interactive_timeout = 600
wait_timeout = 600
tmp_table_size = 32M
max_heap_table_size = 32M
slow_query_log = 1
log_timestamps = SYSTEM
slow_query_log_file = /home/mysqlfile/mysqllogs80/slow.log
log-error = /home/mysqlfile/mysqllogs80/error.log
long_query_time = 1
log_queries_not_using_indexes =1
log_throttle_queries_not_using_indexes = 60
min_examined_row_limit = 100
log_slow_admin_statements = 1
log_slow_slave_statements = 1
server-id = 52113306
log-bin = /home/mysqlfile/mysqllogs80/mysqlbinlog/mysqlbinlog
sync_binlog = 500
binlog_cache_size = 4M
max_binlog_cache_size = 2G
max_binlog_size = 1G

#注意：MySQL 8.0开始，binlog_expire_logs_seconds选项也存在的话，会忽略expire_logs_days选项
expire_logs_days = 2

slave-skip-errors=1396,1141
#replicate_do_db=shys_test
replicate_do_db=shys_canary_test
mysqlx=0
#skip-log-bin
lower_case_table_names=1
sql_mode='STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION'
log_bin_trust_function_creators = 1
transaction_isolation = read-committed
skip_ssl
relay_log = /home/mysqlfile/mysqllogs80/relay-log/relay.log
plugin_dir=/usr/local/mysql80/lib/plugin
plugin_load = "rpl_semi_sync_master=semisync_master.so;rpl_semi_sync_slave=semisync_slave.so"
loose_rpl_semi_sync_master_enabled = 1
loose_rpl_semi_sync_slave_enabled = 1
loose_rpl_semi_sync_master_timeout = 5000
loose_rpl_semi_sync_master_wait_point = AFTER_SYNC
loose_rpl_semi_sync_master_wait_for_slave_count = 1
slave-parallel-type=LOGICAL_CLOCK
slave-parallel-workers=8 
#slave_preserve_commit_order=1
innodb_print_all_deadlocks=on

master_info_repository = TABLE
relay_log_info_repository = TABLE
gtid_mode = on
enforce_gtid_consistency = 1
log_slave_updates
slave-rows-search-algorithms = 'INDEX_SCAN,HASH_SCAN'
binlog_format = row
binlog_checksum = 1
relay_log_recovery = 1
relay-log-purge = 1
key_buffer_size = 32M
read_buffer_size = 8M
read_rnd_buffer_size = 4M
bulk_insert_buffer_size = 64M
myisam_sort_buffer_size = 128M
myisam_max_sort_file_size = 10G
myisam_repair_threads = 1
lock_wait_timeout = 3600
explicit_defaults_for_timestamp = 1
innodb_thread_concurrency = 0
innodb_sync_spin_loops = 100
innodb_spin_wait_delay = 30

#transaction_isolation = REPEATABLE-READ
#innodb_additional_mem_pool_size = 16M
innodb_buffer_pool_size = 12938M
innodb_buffer_pool_instances = 4
innodb_buffer_pool_load_at_startup = 1
innodb_buffer_pool_dump_at_shutdown = 1
innodb_data_file_path = ibdata1:1G:autoextend
innodb_flush_log_at_trx_commit = 2
innodb_log_buffer_size = 32M
innodb_log_file_size = 2G
innodb_log_files_in_group = 2
innodb_max_undo_log_size = 4G
innodb_undo_directory = /home/mysqlfile/mysqllogs80/undolog
innodb_undo_tablespaces = 95

# 根据您的服务器IOPS能力适当调整
# 一般配普通SSD盘的话，可以调整到 10000 - 20000
# 配置高端PCIe SSD卡的话，则可以调整的更高，比如 50000 - 80000
innodb_io_capacity = 6000
innodb_io_capacity_max = 8000
innodb_flush_sync = 0
innodb_flush_neighbors = 0
innodb_write_io_threads = 8
innodb_read_io_threads = 8
innodb_purge_threads = 4
innodb_page_cleaners = 4
innodb_open_files = 65535
innodb_max_dirty_pages_pct = 50
innodb_flush_method = O_DIRECT
innodb_lru_scan_depth = 4000
innodb_checksum_algorithm = crc32
innodb_lock_wait_timeout = 10
innodb_rollback_on_timeout = 1
innodb_print_all_deadlocks = 1
innodb_file_per_table = 1
innodb_online_alter_log_max_size = 4G
innodb_stats_on_metadata = 0
innodb_undo_log_truncate = 1

# some var for MySQL 8
log_error_verbosity = 3
innodb_print_ddl_logs = 1
binlog_expire_logs_seconds = 604800
#innodb_dedicated_server = 0

innodb_status_file = 1
#注意: 开启 innodb_status_output & innodb_status_output_locks 后, 可能会导致log-error文件增长较快
innodb_status_output = 0
innodb_status_output_locks = 0

#performance_schema
performance_schema = 1
performance_schema_instrument = '%memory%=on'
performance_schema_instrument = '%lock%=on'

#innodb monitor
innodb_monitor_enable="module_innodb"
innodb_monitor_enable="module_server"
innodb_monitor_enable="module_dml"
innodb_monitor_enable="module_ddl"
innodb_monitor_enable="module_trx"
innodb_monitor_enable="module_os"
innodb_monitor_enable="module_purge"
innodb_monitor_enable="module_log"
innodb_monitor_enable="module_lock"
innodb_monitor_enable="module_buffer"
innodb_monitor_enable="module_index"
innodb_monitor_enable="module_ibuf_system"
innodb_monitor_enable="module_buffer_page"
innodb_monitor_enable="module_adaptive_hash"

[mysqldump]
quick
max_allowed_packet = 256M

**Comment by liuhr** [comment]
mysql配置文件中添加以下配置，就可以了。
default_authentication_plugin  =mysql_native_password

**Comment by zzxcong** [comment]
确实mysql配置文件中添加以下配置，就可以了。
default_authentication_plugin =mysql_native_password


谢谢
